import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { normalizeRepos, buildModel } from '../scripts/lib/model.mjs';
import { parseHeader, AUTO_START, AUTO_END } from '../scripts/lib/notes.mjs';
import {
  escapeMd, renderAutoBlock, renderDashboard, renderIndex, renderStarred,
  renderAuditsReadme, buildOutputs,
} from '../scripts/lib/render.mjs';

const pages = JSON.parse(readFileSync(new URL('./fixtures/repos-pages.json', import.meta.url)));
const NOW = new Date('2026-09-27T12:00:00Z');
const GENERATED = '2026-09-27 12:00 UTC';

const NOTE_TEXTS = {
  'app-one.md': '# app-one\n\n**Category:** Apps  \n**Uses:** svc-core  \n\n## Notes\nMine.\n',
  'svc-core.md': '# svc-core\n\n**Category:** Libraries  \n\n## Notes\n',
  'hidden-repo.md': '# hidden-repo\n\n**Track:** no  \n',
  'upstream-fork.md': '# upstream-fork\n\n**Track:** upstream  \n',
};

function model(now = NOW) {
  const notes = Object.entries(NOTE_TEXTS).map(([file, text]) => ({ file, header: parseHeader(text) }));
  return buildModel({ repos: normalizeRepos(pages), notes, now, owner: 'ChadFarrow' });
}
const project = (m, name) => m.projects.find((p) => p.name === name);
const dashboard = (opts = {}) =>
  renderDashboard(model(), { generatedAt: GENERATED, degradedReason: null, base: '', problems: [], ...opts });

// ---------- escapeMd ----------

test('escapeMd escapes markdown characters that break titles', () => {
  assert.equal(escapeMd('<podcast:category> *a* _b_ [c] `d` \\'), '\\<podcast:category\\> \\*a\\* \\_b\\_ \\[c\\] \\`d\\` \\\\');
  assert.equal(escapeMd('line\none'), 'line one');
});

// ---------- auto block ----------

test('renderAutoBlock matches the expected block for svc-core', () => {
  assert.equal(renderAutoBlock(project(model(), 'svc-core'), model()), [
    '<!-- Generated by scripts/sync.mjs. Do not edit between the AUTO markers. -->',
    '## Live status',
    '',
    '- **Repo:** [ChadFarrow/svc-core](https://github.com/ChadFarrow/svc-core) · JavaScript',
    '- **Used by:** [app-one](app-one.md)',
    '',
    '### Issues (5)',
    '',
    '- [#13 Bump nostr-tools](https://github.com/ChadFarrow/svc-core/issues/13) — opened 2026-09-06',
    '- [#8 Self and unknown markers](https://github.com/ChadFarrow/svc-core/issues/8) — opened 2026-09-23',
    '- [#7 Rate limit for app-one](https://github.com/ChadFarrow/svc-core/issues/7) — opened 2026-09-24 · for [app-one](app-one.md)',
    '- [2 more on GitHub](https://github.com/ChadFarrow/svc-core/issues)',
  ].join('\n'));
});

test('renderAutoBlock does not depend on the date', () => {
  const later = new Date('2027-03-01T00:00:00Z');
  for (const name of ['app-one', 'svc-core', 'fork-thing', 'secret-repo', 'hidden-repo']) {
    assert.equal(
      renderAutoBlock(project(model(later), name), model(later)),
      renderAutoBlock(project(model(), name), model()),
      name,
    );
  }
});

test('renderAutoBlock shows uses, PR states, items opened elsewhere and branches', () => {
  const block = renderAutoBlock(project(model(), 'app-one'), model());
  assert.match(block, /- \*\*Uses:\*\* \[svc-core\]\(svc-core\.md\) \(5 issues\)/);
  assert.match(block, /### Pull requests \(8\)/);
  assert.match(block, /\[#2 Draft thing\]\(\S+\) — opened 2026-08-01 · draft/);
  assert.match(block, /\[#3 Conflicted\]\(\S+\) — opened 2026-08-01 · merge conflict/);
  assert.match(block, /\[#9 Failing\]\(\S+\) — opened 2026-08-01 · checks failing/);
  assert.match(block, /\[#10 Pending\]\(\S+\) — opened 2026-08-01 · checks pending/);
  assert.match(block, /\[#11 Bot bump\]\(\S+\) — opened 2026-08-01 · by vercel/);
  assert.doesNotMatch(block, /UNKNOWN|MERGEABLE/);
  assert.match(block, /### Opened elsewhere for this project \(2\)/);
  assert.match(block, /- \[secret-repo #3 Helper for app-one\]\(https:\/\/github\.com\/ChadFarrow\/secret-repo\/pull\/3\) — PR/);
  assert.match(block, /### Branches with no open PR \(2\)/);
  assert.match(block, /- \[`newer-branch`\]\(https:\/\/github\.com\/ChadFarrow\/app-one\/tree\/newer-branch\)/);
  assert.match(block, /\\<podcast:category\\> \\\*now\\\*/);
});

test('renderAutoBlock says so when there is no open work', () => {
  assert.match(renderAutoBlock(project(model(), 'upstream-fork'), model()), /_No open work\._/);
  assert.match(renderAutoBlock(project(model(), 'upstream-fork'), model()), /fork of someone\/upstream-fork/);
  assert.match(renderAutoBlock(project(model(), 'secret-repo'), model()), /· private/);
});

test('renderAutoBlock marks an untracked project', () => {
  const block = renderAutoBlock(project(model(), 'hidden-repo'), model());
  assert.match(block, /Not tracked/);
  assert.doesNotMatch(block, /Hidden issue/);
});

// ---------- dashboard ----------

test('the dashboard has no checkboxes and every list item has a link', () => {
  const md = dashboard();
  assert.doesNotMatch(md, /- \[ \]/);
  for (const line of md.split('\n').filter((l) => l.startsWith('- '))) {
    assert.match(line, /\]\(/, line);
  }
});

test('the dashboard lists ready-but-idle PRs, longest idle first', () => {
  const md = dashboard();
  const a = md.indexOf('[#6 Unknown merge state]');
  const b = md.indexOf('[#1 Ready one]');
  assert.ok(a > 0 && b > a);
  assert.match(md, /idle 17 days · no checks/);
  assert.match(md, /idle 7 days · checks passing/);
});

test('the dashboard groups issues with the same title into one line', () => {
  const md = dashboard();
  assert.match(md, /- Bump nostr-tools — \[app-one #14\]\(\S+\) · \[svc-core #13\]\(\S+\)/);
  assert.equal(md.split('[#13 Bump nostr-tools]').length, 1);
});

test('the dashboard lists issues by project with author, comments and marker', () => {
  const md = dashboard();
  assert.match(md, /\[#4 Support \\<podcast:category\\> \\\*now\\\*\]\(\S+\) — opened 2 days ago · by outsider · 2 comments/);
  assert.match(md, /\[#7 Rate limit for app-one\]\(\S+\) — opened 3 days ago · for \[app-one\]\(projects\/app-one\.md\)/);
});

test('the dashboard leaves out untracked repos', () => {
  const md = dashboard();
  assert.doesNotMatch(md, /Hidden issue/);
  assert.doesNotMatch(md, /\[hidden-repo\]/);
});

test('the dashboard groups projects by category, Uncategorized last', () => {
  const md = dashboard();
  const apps = md.indexOf('### Apps');
  const libs = md.indexOf('### Libraries');
  const unc = md.indexOf('### Uncategorized');
  assert.ok(apps > 0 && libs > apps && unc > libs);
  assert.match(md, /#### \[app-one\]\(projects\/app-one\.md\)/);
});

test('the dashboard lists quiet and stale projects', () => {
  const md = dashboard();
  assert.match(md, /### Quiet — no open work\n\n\[upstream-fork\]\(projects\/upstream-fork\.md\)/);
  assert.match(md, /## Stale — no push in 180\+ days\n\n- \[fork-thing\]\(projects\/fork-thing\.md\) — last push 2026-01-01 · fork/);
});

test('the dashboard caps a project at 10 branches', () => {
  const m = model();
  const p = project(m, 'fork-thing');
  p.orphanBranches = Array.from({ length: 13 }, (_, i) => ({ name: `b${i}`, committedDate: null }));
  const md = renderDashboard(m, { generatedAt: GENERATED, degradedReason: null, base: '', problems: [] });
  assert.match(md, /`b9`/);
  assert.doesNotMatch(md, /`b10`/);
  assert.match(md, /- \[3 more branches with no PR\]\(projects\/fork-thing\.md\)/);
});

test('the audit copy prefixes every relative link with ../', () => {
  const md = dashboard({ base: '../' });
  assert.match(md, /\(\.\.\/projects\/app-one\.md\)/);
  assert.match(md, /\(\.\.\/INDEX\.md\)/);
  assert.doesNotMatch(md, /\]\(projects\//);
});

test('the dashboard shows the degraded banner and the problems', () => {
  const md = dashboard({ degradedReason: '`AUDIT_TOKEN` is not set', problems: ['bad thing'] });
  assert.match(md, /> \[!WARNING\]\n> \*\*This dashboard is incomplete — private repositories are missing\.\*\*/);
  assert.match(md, /> `AUDIT_TOKEN` is not set, so this ran/);
  assert.match(md, /## Note problems\n\n- bad thing/);
  assert.doesNotMatch(dashboard(), /WARNING|Note problems/);
});

// ---------- index, starred, audits ----------

test('renderIndex groups every repo by category with flags', () => {
  const md = renderIndex(model());
  assert.match(md, /## Apps\n\n- \[app-one\]\(projects\/app-one\.md\) - The main app \(`TypeScript`\)/);
  assert.match(md, /- \[fork-thing\]\(projects\/fork-thing\.md\) - No description · fork/);
  assert.match(md, /- \[hidden-repo\]\(projects\/hidden-repo\.md\) - Not wanted \(`Go`\) · not tracked/);
  assert.match(md, /- \[secret-repo\]\(projects\/secret-repo\.md\) - Private work \(`Rust`\) · private/);
  assert.doesNotMatch(md, /ISSUES\.md|PULL_REQUESTS\.md|BRANCHES\.md|\d{2}:\d{2}/);
});

test('renderStarred matches the old jq output exactly', () => {
  const stars = [
    { name: 'nostr-relay', html_url: 'https://github.com/a/nostr-relay', description: 'Relay' },
    { name: 'lnurl-podcast', html_url: 'https://github.com/a/lnurl-podcast', description: null },
    { name: 'misc', html_url: 'https://github.com/a/misc', description: '' },
  ];
  assert.equal(renderStarred(stars, GENERATED), [
    '# Starred Repos',
    '',
    '*Auto-synced every 4 hours*',
    '',
    '## Nostr',
    '- [nostr-relay](https://github.com/a/nostr-relay) - Relay',
    '',
    '## Lightning',
    '- [lnurl-podcast](https://github.com/a/lnurl-podcast) - No description',
    '',
    '## Podcasting',
    '- [lnurl-podcast](https://github.com/a/lnurl-podcast) - No description',
    '',
    '## Other',
    '- [misc](https://github.com/a/misc) - ',
    '',
    '---',
    `*Last synced: ${GENERATED}*`,
    '',
  ].join('\n'));
});

test('renderAuditsReadme lists the dated files newest first', () => {
  assert.equal(renderAuditsReadme(['2026-09-26.md', 'README.md', '2026-09-27.md']), [
    '# Audit History',
    '',
    'Point-in-time cross-repo sweeps. [LATEST.md](../LATEST.md) is the newest entry.',
    '',
    '- [2026-09-27](2026-09-27.md)',
    '- [2026-09-26](2026-09-26.md)',
    '',
  ].join('\n'));
});

// ---------- buildOutputs ----------

function outputs(noteTexts = NOTE_TEXTS, degradedReason = null) {
  return buildOutputs({
    owner: 'ChadFarrow',
    now: NOW,
    repos: normalizeRepos(pages),
    stars: [],
    notes: Object.entries(noteTexts).map(([file, text]) => ({ file, text })),
    auditFiles: ['2026-09-26.md', 'README.md'],
    degradedReason,
  });
}

test('buildOutputs writes every generated file', () => {
  const { files } = outputs();
  for (const f of ['LATEST.md', 'audits/2026-09-27.md', 'audits/README.md', 'INDEX.md', 'references/starred.md']) {
    assert.ok(files.has(f), f);
  }
  assert.match(files.get('audits/README.md'), /2026-09-27\.md[\s\S]*2026-09-26\.md/);
});

test('buildOutputs only adds to an existing note', () => {
  const { files } = outputs();
  const note = files.get('projects/app-one.md');
  assert.ok(note.startsWith(NOTE_TEXTS['app-one.md'].trimEnd()));
  assert.ok(note.includes(`${AUTO_START}\n<!-- Generated`));
  assert.ok(note.endsWith(`${AUTO_END}\n`));
});

test('buildOutputs creates a stub for a repo with no note', () => {
  const { files } = outputs();
  const stub = files.get('projects/secret-repo.md');
  assert.match(stub, /^# secret-repo\n/);
  assert.match(stub, /## Description\nPrivate work\n/);
  assert.match(stub, /## Live status/);
});

test('buildOutputs leaves a note with broken markers alone and reports it', () => {
  const texts = { ...NOTE_TEXTS, 'svc-core.md': `# svc-core\n${AUTO_START}\n${AUTO_START}\n` };
  const { files, problems } = outputs(texts);
  assert.equal(files.has('projects/svc-core.md'), false);
  assert.ok(problems.some((p) => p.includes('projects/svc-core.md')));
  assert.match(files.get('LATEST.md'), /## Note problems[\s\S]*projects\/svc-core\.md/);
});

test('buildOutputs is stable: a second run over its own output changes no note', () => {
  const first = outputs().files;
  const texts = {};
  for (const [path, text] of first) if (path.startsWith('projects/')) texts[path.slice('projects/'.length)] = text;
  const second = outputs(texts).files;
  for (const [path, text] of second) if (path.startsWith('projects/')) assert.equal(text, first.get(path), path);
});
