// Pure markdown output: model → LATEST.md, audits, INDEX.md, the note blocks and
// references/starred.md. `buildOutputs` ties it together and returns every file the
// sync should write, keyed by path relative to the repo root.

import { buildModel, IDLE_DAYS, STALE_DAYS } from './model.mjs';
import { parseHeader, spliceAutoBlock, stubNote } from './notes.mjs';

const MD_SPECIAL = /[\\[\]<>*_`]/g;

export function escapeMd(s) {
  return String(s ?? '').replace(/\s*\n\s*/g, ' ').replace(MD_SPECIAL, (c) => `\\${c}`);
}

const plural = (n, word, words = `${word}s`) => `${n} ${n === 1 ? word : words}`;
const day = (iso) => iso.slice(0, 10);

function ago(iso, now) {
  const mins = Math.floor((now - new Date(iso)) / 60000);
  const unit = (n, word) => `${plural(n, word)} ago`;
  if (mins < 1) return 'just now';
  if (mins < 60) return unit(mins, 'minute');
  const hours = Math.floor(mins / 60);
  if (hours < 24) return unit(hours, 'hour');
  const days = Math.floor(hours / 24);
  if (days < 60) return unit(days, 'day');
  if (days < 730) return unit(Math.floor(days / 30), 'month');
  return unit(Math.floor(days / 365), 'year');
}

const noteFile = (model, name) => model.index.get(name).noteFile ?? `${name}.md`;
const noteLink = (model, name, prefix) => `[${name}](${prefix}${noteFile(model, name)})`;
const branchUrl = (p, name) => `${p.url}/tree/${name.split('/').map(encodeURIComponent).join('/')}`;

function workCounts(p) {
  const parts = [];
  if (p.prsTotal) parts.push(plural(p.prsTotal, 'PR'));
  if (p.issuesTotal) parts.push(plural(p.issuesTotal, 'issue'));
  return parts.length ? parts.join(', ') : 'no open work';
}

function prTags(pr, owner) {
  const tags = [];
  if (pr.isDraft) tags.push('draft');
  if (pr.mergeable === 'CONFLICTING') tags.push('merge conflict');
  if (pr.checks === 'FAILURE' || pr.checks === 'ERROR') tags.push('checks failing');
  if (pr.checks === 'PENDING' || pr.checks === 'EXPECTED') tags.push('checks pending');
  if (pr.author !== owner) tags.push(`by ${pr.author}`);
  return tags;
}

const forText = (item, model, prefix) =>
  item.for.length ? [`for ${item.for.map((n) => noteLink(model, n, prefix)).join(', ')}`] : [];

const line = (link, details) => `- ${link}${details.length ? ` — ${details.join(' · ')}` : ''}`;
const itemLink = (item, label = `#${item.number}`) => `[${label} ${escapeMd(item.title)}](${item.url})`;

function repoFacts(p) {
  const facts = [`[ChadFarrow/${p.name}](${p.url})`];
  if (p.language) facts.push(p.language);
  if (p.isFork) facts.push(p.parent ? `fork of ${p.parent}` : 'fork');
  if (p.isPrivate) facts.push('private');
  return facts.join(' · ');
}

// ---------- the note block ----------

// Everything in here must depend only on GitHub data, never on the clock: a run
// that changes nothing must leave every hand-edited note byte-identical.
export function renderAutoBlock(p, model) {
  const out = [
    '<!-- Generated by scripts/sync.mjs. Do not edit between the AUTO markers. -->',
    '## Live status',
    '',
    `- **Repo:** ${repoFacts(p)}`,
  ];
  if (p.track === 'no') {
    out.push('', '_Not tracked: this note has `**Track:** no`, so the dashboard leaves the project out._');
    return out.join('\n');
  }
  if (p.uses.length) {
    out.push(`- **Uses:** ${p.uses.map((n) => `${noteLink(model, n, '')} (${workCounts(model.index.get(n))})`).join(', ')}`);
  }
  if (p.usedBy.length) out.push(`- **Used by:** ${p.usedBy.map((n) => noteLink(model, n, '')).join(', ')}`);

  const byNumber = (a, b) => b.number - a.number;
  const more = (shown, total, path) =>
    total > shown ? [`- [${total - shown} more on GitHub](${model.index.get(p.name).url}/${path})`] : [];

  const sections = [];
  if (p.prsTotal) {
    sections.push([`### Pull requests (${p.prsTotal})`, '',
      ...[...p.prs].sort(byNumber).map((pr) =>
        line(itemLink(pr), [`opened ${day(pr.createdAt)}`, ...prTags(pr, model.owner), ...forText(pr, model, '')])),
      ...more(p.prs.length, p.prsTotal, 'pulls')]);
  }
  if (p.issuesTotal) {
    sections.push([`### Issues (${p.issuesTotal})`, '',
      ...[...p.issues].sort(byNumber).map((i) =>
        line(itemLink(i), [`opened ${day(i.createdAt)}`, ...(i.author !== model.owner ? [`by ${i.author}`] : []),
          ...forText(i, model, '')])),
      ...more(p.issues.length, p.issuesTotal, 'issues')]);
  }
  if (p.openedElsewhere.length) {
    sections.push([`### Opened elsewhere for this project (${p.openedElsewhere.length})`, '',
      ...[...p.openedElsewhere].sort((a, b) => a.repo.localeCompare(b.repo) || b.number - a.number)
        .map((e) => line(itemLink(e, `${e.repo} #${e.number}`), [e.kind, `opened ${day(e.createdAt)}`]))]);
  }
  if (p.orphanBranches.length) {
    sections.push([`### Branches with no open PR (${p.orphanBranches.length})`, '',
      ...[...p.orphanBranches].sort((a, b) => a.name.localeCompare(b.name))
        .map((b) => `- [\`${b.name}\`](${branchUrl(p, b.name)})`)]);
  }
  if (!sections.length) out.push('', '_No open work._');
  for (const s of sections) out.push('', ...s);
  return out.join('\n');
}

// ---------- the dashboard ----------

const byCategory = (a, b) =>
  (a === 'Uncategorized') - (b === 'Uncategorized') || a.localeCompare(b, 'en', { sensitivity: 'base' });

function groupByCategory(projects) {
  const groups = new Map();
  for (const p of projects) {
    if (!groups.has(p.category)) groups.set(p.category, []);
    groups.get(p.category).push(p);
  }
  return [...groups.entries()].sort(([a], [b]) => byCategory(a, b));
}

const hasWork = (p) => p.prsTotal || p.issuesTotal || p.orphanBranches.length || p.openedElsewhere.length;
const newestFirst = (a, b) => b.updatedAt.localeCompare(a.updatedAt);

export function renderDashboard(model, { generatedAt, degradedReason, base, problems }) {
  const { now, owner } = model;
  const notes = `${base}projects/`;
  const tracked = model.projects.filter((p) => p.track !== 'no');
  const untracked = model.projects.length - tracked.length;
  const sum = (f) => tracked.reduce((n, p) => n + f(p), 0);
  const out = [`# Dashboard — ${generatedAt}`, ''];

  if (degradedReason) {
    out.push(
      '> [!WARNING]',
      '> **This dashboard is incomplete — private repositories are missing.**',
      '>',
      `> ${degradedReason}, so this ran with the default \`GITHUB_TOKEN\`, which`,
      '> only sees public repos. Every section below is public-only; open PRs,',
      '> issues and branches in private repos are absent, not resolved.',
      '>',
      '> Fix: rotate the secret (repo Settings → Secrets and variables → Actions →',
      '> `AUDIT_TOKEN`) with a PAT carrying `repo` scope, then re-run the workflow.',
      '',
    );
  }

  out.push(
    `${plural(sum((p) => p.prsTotal), 'open PR')} · ${plural(sum((p) => p.issuesTotal), 'open issue')} · `
      + `${plural(sum((p) => p.orphanBranches.length), 'branch', 'branches')} with no PR · `
      + `${plural(tracked.length, 'tracked repo')}${untracked ? ` (${untracked} not tracked)` : ''}`,
    '',
    `[Project index](${base}INDEX.md) · [Dashboard history](${base}audits/README.md)`,
    '',
    '## Needs you now',
    '',
    `### Ready to merge — idle ${IDLE_DAYS}+ days (${model.readyIdle.length})`,
    '',
  );
  if (model.readyIdle.length) {
    for (const { project, pr, idleDays } of model.readyIdle) {
      out.push(`- **${project.name}** ${itemLink(pr)} — idle ${plural(idleDays, 'day')} · `
        + `${pr.checks === 'SUCCESS' ? 'checks passing' : 'no checks'}`);
    }
  } else {
    out.push('_None._');
  }

  // Issues: one line for titles open in several repos, then the rest by project.
  const issues = tracked.flatMap((p) => p.issues.map((i) => ({ ...i, repo: p.name })));
  const byTitle = new Map();
  for (const i of issues) {
    const key = i.title.trim().toLowerCase();
    if (!byTitle.has(key)) byTitle.set(key, []);
    byTitle.get(key).push(i);
  }
  const shared = [...byTitle.values()].filter((g) => new Set(g.map((i) => i.repo)).size > 1);
  const sharedUrls = new Set(shared.flat().map((i) => i.url));
  out.push('', `### Open issues (${issues.length})`);
  if (shared.length) {
    out.push('', '**Same title in several repos**', '');
    const latest = (g) => g.map((i) => i.updatedAt).sort().at(-1);
    for (const g of shared.sort((a, b) => latest(b).localeCompare(latest(a)))) {
      const links = [...g].sort((a, b) => a.repo.localeCompare(b.repo)).map((i) => `[${i.repo} #${i.number}](${i.url})`);
      out.push(`- ${escapeMd(g[0].title.trim())} — ${links.join(' · ')}`);
    }
  }
  const issueGroups = tracked
    .map((p) => ({ p, list: p.issues.filter((i) => !sharedUrls.has(i.url)) }))
    .filter((g) => g.list.length)
    .map((g) => ({ ...g, list: [...g.list].sort(newestFirst) }))
    .sort((a, b) => newestFirst(a.list[0], b.list[0]));
  for (const { p, list } of issueGroups) {
    out.push('', `**${noteLink(model, p.name, notes)}**`, '');
    for (const i of list) {
      const details = [`opened ${ago(i.createdAt, now)}`];
      if (i.author !== owner) details.push(`by ${i.author}`);
      if (i.comments) details.push(plural(i.comments, 'comment'));
      out.push(line(itemLink(i), [...details, ...forText(i, model, notes)]));
    }
  }
  if (!issues.length) out.push('', '_None._');

  // Projects with open work, by category.
  out.push('', '## Projects');
  const active = tracked.filter(hasWork).sort((a, b) => b.lastActivity.localeCompare(a.lastActivity));
  for (const [category, projects] of groupByCategory(active)) {
    out.push('', `### ${category}`);
    for (const p of projects) {
      const facts = [];
      if (p.prsTotal) facts.push(plural(p.prsTotal, 'PR'));
      if (p.issuesTotal) facts.push(plural(p.issuesTotal, 'issue'));
      if (p.orphanBranches.length) facts.push(`${plural(p.orphanBranches.length, 'branch', 'branches')} with no PR`);
      if (p.uses.length) {
        facts.push(`uses ${p.uses.map((n) => `${noteLink(model, n, notes)} (${workCounts(model.index.get(n))})`).join(', ')}`);
      }
      if (p.usedBy.length) facts.push(`used by ${p.usedBy.map((n) => noteLink(model, n, notes)).join(', ')}`);
      out.push('', `#### ${noteLink(model, p.name, notes)}`, '', facts.join(' · '));

      const items = [];
      for (const pr of p.prs) {
        items.push(line(`PR ${itemLink(pr)}`, [`opened ${ago(pr.createdAt, now)}`, ...prTags(pr, owner), ...forText(pr, model, notes)]));
      }
      for (const e of p.openedElsewhere) {
        items.push(line(`Opened elsewhere: ${itemLink(e, `${e.repo} #${e.number}`)}`, [e.kind, `opened ${ago(e.createdAt, now)}`]));
      }
      for (const b of p.orphanBranches.slice(0, 10)) items.push(`- Branch [\`${b.name}\`](${branchUrl(p, b.name)}) — no PR`);
      if (p.orphanBranches.length > 10) {
        items.push(`- [${p.orphanBranches.length - 10} more branches with no PR](${notes}${noteFile(model, p.name)})`);
      }
      if (items.length) out.push('', ...items);
    }
  }
  const quiet = tracked.filter((p) => !hasWork(p));
  if (quiet.length) {
    out.push('', '### Quiet — no open work', '', quiet.map((p) => noteLink(model, p.name, notes)).join(' · '));
  }

  out.push('', `## Stale — no push in ${STALE_DAYS}+ days`, '');
  if (model.stale.length) {
    for (const p of model.stale) {
      const flags = [...(p.isFork ? ['fork'] : []), ...(p.isPrivate ? ['private'] : [])];
      out.push(line(noteLink(model, p.name, notes), [`last push ${day(p.pushedAt)}`, ...flags]));
    }
  } else {
    out.push('_None._');
  }

  if (problems.length) out.push('', '## Note problems', '', ...problems.map((p) => `- ${p}`));
  return `${out.join('\n')}\n`;
}

// ---------- the other generated files ----------

export function renderIndex(model) {
  const out = [
    '# Projects',
    '',
    'One note per repository in [`projects/`](projects/). The [dashboard](LATEST.md) lists the open work.',
  ];
  for (const [category, projects] of groupByCategory(model.projects)) {
    out.push('', `## ${category}`, '');
    for (const p of projects) {
      const flags = [];
      if (p.isFork) flags.push('fork');
      if (p.isPrivate) flags.push('private');
      if (p.track === 'no') flags.push('not tracked');
      const desc = p.description ? escapeMd(p.description) : 'No description';
      out.push(`- ${noteLink(model, p.name, 'projects/')} - ${desc}${p.language ? ` (\`${p.language}\`)` : ''}`
        + flags.map((f) => ` · ${f}`).join(''));
    }
  }
  out.push(
    '',
    '---',
    '',
    '## Reference',
    '- [PC2.0 Specs Reference](PC2.0-SPECS.md)',
    '- [References](references/README.md) - General bookmarks & links',
    '- [GitHub Profile](https://github.com/ChadFarrow)',
  );
  return `${out.join('\n')}\n`;
}

// A straight port of the old jq: the sections overlap on purpose, "Other" is what
// matches none, and an empty description stays empty (jq's `//` only replaces null).
const STAR_SECTIONS = [
  ['Nostr', 'nostr|nip|amber|aegis|blossom|bloom|relay|jumble|vnak'],
  ['Lightning', 'lightning|lnurl|bolt|alby|coinos|breez|spark'],
  ['Podcasting', 'podcast|rss|feed|boost|v4v|podping'],
];

export function renderStarred(stars, generatedAt) {
  const item = (s) => `- [${s.name}](${s.html_url}) - ${s.description ?? 'No description'}`;
  const out = ['# Starred Repos', '', '*Auto-synced every 6 hours*', ''];
  for (const [title, pattern] of STAR_SECTIONS) {
    const re = new RegExp(pattern, 'i');
    out.push(`## ${title}`, ...stars.filter((s) => re.test(s.name)).map(item), '');
  }
  const any = new RegExp(STAR_SECTIONS.map(([, p]) => p).join('|'), 'i');
  out.push('## Other', ...stars.filter((s) => !any.test(s.name)).map(item), '');
  out.push('---', `*Last synced: ${generatedAt}*`, '');
  return out.join('\n');
}

export function renderAuditsReadme(files) {
  const dated = files.filter((f) => f.endsWith('.md') && !f.includes('README')).sort().reverse();
  return [
    '# Audit History',
    '',
    'Point-in-time cross-repo sweeps. [LATEST.md](../LATEST.md) is the newest entry.',
    '',
    ...dated.map((f) => `- [${f.slice(0, -3)}](${f})`),
    '',
  ].join('\n');
}

// notes: [{ file, text }] from projects/. auditFiles: names already in audits/.
export function buildOutputs({ owner, now, repos, stars, notes, auditFiles, degradedReason }) {
  const parsed = notes.map((n) => ({ ...n, header: parseHeader(n.text) }));
  const model = buildModel({ repos, notes: parsed, now, owner, degraded: Boolean(degradedReason) });
  const problems = [...model.problems];
  const files = new Map();

  for (const p of model.projects) {
    const block = renderAutoBlock(p, model);
    if (p.noteFile) {
      const result = spliceAutoBlock(parsed.find((n) => n.file === p.noteFile).text, block);
      if (result.error) problems.push(`\`projects/${p.noteFile}\`: ${result.error}`);
      else files.set(`projects/${p.noteFile}`, result.text);
    } else {
      const stub = stubNote({ name: p.name, description: escapeMd(p.description) });
      files.set(`projects/${p.name}.md`, spliceAutoBlock(stub, block).text);
    }
  }

  const generatedAt = `${now.toISOString().slice(0, 10)} ${now.toISOString().slice(11, 16)} UTC`;
  const date = now.toISOString().slice(0, 10);
  const opts = { generatedAt, degradedReason, problems };
  files.set('LATEST.md', renderDashboard(model, { ...opts, base: '' }));
  files.set(`audits/${date}.md`, renderDashboard(model, { ...opts, base: '../' }));
  files.set('audits/README.md', renderAuditsReadme([...new Set([...auditFiles, `${date}.md`])]));
  files.set('INDEX.md', renderIndex(model));
  files.set('references/starred.md', renderStarred(stars, generatedAt));
  return { files, problems };
}
